# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Annotags
#email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Annotags is a decentralized literary annotation sharing system. It provides
  a consistent system for identifying books, pages, and selections/highlights.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://annotags.github.io" # the base hostname & protocol for your site
twitter_username: annotags
github_username:  annotags

# Build settings
markdown: kramdown
